site: Mostly Cats

title: Mostly Cats
url: https://www.mostlycats.org
baseurl: 

collections:
  posts:
    output: true
    permalink: /post/:slug.html
  projects:
    output: true
    permalink: /projects/:slug.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "summer"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-gallery-generator
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-google-photos
  - jekyll-minifier

paginate: 6
paginate_path: "/blog/page:num/"

gallery:
  dir: photos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "photos"           # Title for gallery index page
  title_prefix: "photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "name"        # How to sort galleries on the index page.
  default_image_sort:       "naturalized"

  # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)

  # The following options are for individual galleries.
  galleries:
    wedding:
      best_image: IMG_0947.jpg
      desc: 10.22.2021

jekyll-minifier:
  preserve_php: false                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: false                # Default: true
  compress_javascript: false         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: true      # Default: false

feed:
  posts_limit: 20