basic_settings:
  site_title: Mostly Cats
  site_tagline: Dispatches from our life together.
  favicon_image: /favicon.ico

header_settings:
  header_image: /images/brick_house_painting.png
  header_image_width: 100%
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Latest'
      url: '/'
    - title: 'Our Wedding'
      url: '/wedding/'
    - title: 'The House'
      url: '/the-house/'
    - title: 'The Homestead'
      url: '/the-homestead'
    - title: 'Projects'
      url: '/projects/'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''


font_settings:
  # font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Muli:400,400i,600" rel="stylesheet">'
  title_font: 'Helvetica, sans-serif'
  body_font: 'Helvetica, sans-serif'
  regular_weight: 400
  bold_weight: 600


advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
